name: Test-OPWM-APP

on:
  workflow_dispatch:
    inputs:
      runTest:
        required: true
        type: boolean
        default: false
      logErrors:
        required: true
        type: boolean
        default: false

jobs:
  test_openweathermap_ubuntu:
    runs-on: ubuntu-latest

    outputs:
      unittest_failed: ${{ steps.run_unittest_tests.outcome == 'failure' }}
      integration_failed: ${{ steps.run_integration_test.outcome == 'failure' }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unittest tests and capture logs
      - name: Run unittest tests
        if: ${{ github.event.inputs.runTest == 'true' }}
        id: run_unittest_tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python -m unittest discover -s . -p "unittest_herman.py" 2>&1 | tee unittest_error.log
        continue-on-error: true

      # Start Flask app
      - name: Run Flask app
        env:
          FLASK_APP: "app.py"
          FLASK_ENV: development
        run: |
          nohup python -m flask run --host=0.0.0.0 &
          sleep 5

      # Run integration test and capture logs
      - name: Run integration test
        id: run_integration_test
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python integrationtest_herman.py 2>&1 | tee integration_error.log
          exit ${PIPESTATUS[0]}
        continue-on-error: true

      # Upload error logs only if the corresponding test failed
      - name: Upload unittest error log
        if: ${{ steps.run_unittest_tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: unittest-error-log
          path: ./unittest_error.log

      - name: Upload integration error log
        if: ${{ steps.run_integration_test.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: integration-error-log
          path: ./integration_error.log

  upload_error_logs:
    runs-on: ubuntu-latest
    needs: test_openweathermap_ubuntu
    # Run only if `logErrors` is true and at least one test has failed
    if: ${{ github.event.inputs.logErrors == 'true' && (needs.test_openweathermap_ubuntu.outputs.unittest_failed == 'true' || needs.test_openweathermap_ubuntu.outputs.integration_failed == 'true') }}

    steps:
      # Download error logs conditionally
      - name: Download unittest error log
        if: ${{ needs.test_openweathermap_ubuntu.outputs.unittest_failed == 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: unittest-error-log

      - name: Download integration error log
        if: ${{ needs.test_openweathermap_ubuntu.outputs.integration_failed == 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: integration-error-log

  build_and_publish_docker:
    runs-on: ubuntu-latest
    needs: test_openweathermap_ubuntu
    # Run only if all tests pass
    if: ${{ needs.test_openweathermap_ubuntu.outputs.unittest_failed == 'false' && needs.test_openweathermap_ubuntu.outputs.integration_failed == 'false' }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/opwm-api:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/opwm-api:latest
